### Create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "price": 999,
  "name": "Product 1"
}

### Get products
GET http://localhost:3000/products/1
Content-Type: application/json

### Update product
PUT http://localhost:3000/products/12
Content-Type: application/json

{
  "price": 999,
  "name": "change id"
}

### Delete product
DELETE http://localhost:3000/products/12223
Content-Type: application/json

{
  "price": 999,
  "name": "change id"
}